import media from "../scripts/mediaMap";

// const media2 = (file) =>
//   new URL(`../assets/media/${file}`, import.meta.url).href;

export const projects = [
  {
    index: 0,
    id: "sabra-mandrake",
    reference: "magazine",
    title: "Sabrá MANDRAKE",
    category: "Editorial Design",
    timeframe: "12 weeks (Sep – Dec 2024)",
    tools: "Procreate, Illustrator, Photoshop, InDesign",
    roles: "Researcher, Editorial Designer, Writer, Visual Designer, Brand Designer, Typographer, Illustrator, Editor",
    problem: [
      "Problem",
      "Most contemporary Colombian media outlets offer a limited or biased perspective of traditional Colombian culture. Although valuable research exists, it is often written in complex academic language that can be difficult to understand or access.",
    ],
    solution: [
      "Solution",
      "I created Sabrá MANDRAKE, a magazine that transforms complex historical and cultural topics about Colombia into engaging visuals and easy-to-understand stories.",
      "Each issue delves into a specific topic, offering readers a narrative-driven analysis of the origins of Colombian traditions, social norms, and behaviors. The issue I designed explores the origins and influences that have shaped Colombian cuisine.",
      "With bold typography, vibrant colors, rich illustrations and photograpies, I aim to capture the essence of Colombian traditions and customs.",
      "The white space is minimal, and the balance between the columns isn't completely symmetrical. This asymmetry lends the layout a dynamic quality, reflecting an unconventional design approach. There are elements that introduce visual disruption, and the use of collage and overlapping elements is quite evident."
    ],
    images: [
      media("p1-1.jpg"),
      media("p1-2.jpg"),
      media("p1-1-stack1.png"),
      media("p1-1-stack2.png"),
      media("p1-1-stack3.png"),
      media("p1-1-stack4.png"),
      media("p1-1-stack5.png"),
      media("p1-3.jpg"),
      media("p1-4.jpg"),
      media("p1-5.jpg"),
      media("p1-6.jpg"),
      media("p1-7.jpg"),
    ],

  },
  {
    index: 1,
    id: "100-years-of-solitude",
    reference: "animation & motion",
    title: "100 Years of Solitude",
    category:"Motion Graphics",
    timeframe: "12 weeks (January – March 2025)",
    tools:
      "Procreate, After Effects, Photoshop, Illustrator, Figma, Final Cut Pro",
      roles: "Visual Designer, Motion Designer, Video Editor",
    problem: [
      "Problem",
      "The complexity and cultural richness of the novel “One Hundred Years of Solitude” are often overlooked or misunderstood, particularly by global audiences who may not be familiar with Latin American history and magical realism.",
    ],
    solution: [
      "Solution",
      "I created a video that introduces viewers to the cultural, historical, and literary significance of the novel “One Hundred Years of Solitude” by Gabriel García Márquez, transforming its complexity into a visually compelling and accessible narrative.",
      "As a Colombian, I understand that this novel is more than just a literary masterpiece—it reflects Latin America’s history, identity, and struggles. Through magical realism, García Márquez tells a story of endless cycles of hope and despair, where the boundaries between reality and fantasy blur, much like they do in the collective memory of my country.",
      "The collage technique was an ideal choice for the video because it reflects the fragmented and cyclical nature of the novel. The collage style layers various visual elements to create a surreal yet cohesive world. This approach offers a dynamic representation of magical realism and lets me capture the essence of the genre.",
      "The layered compositions and surreal visuals in the story are strong symbols of the events that happen in Macondo, the fictional town at the center of the narrative. Although Macondo is not found on any map, it represents Colombia and the complexities of Latin America."
    ],
    images: [
      media("p2-1.jpg"),
      media("p2-2.jpg"),
      media("p2-stack1.png"),
      media("p2-stack2.png"),
      media("p2-stack3.png"),
      media("p2-stack4.png"),
      media("p2-stack5.png"),
      media("p2-3.jpg"),
      media("p2-4.jpg"),
      media("p2-5.jpg"),      
      media("p2-6.gif"),
      media("p2-7.gif"),
    ],
  },
  {
    index: 2,
    id: "bubble-brand",
    reference: "branding & UX/UI",
    title: "bubble, probiotic soda",
    category: "Branding + UX/UI", 
    timeframe: "12 weeks (January – March 2024)",
    tools: "Figma, Illustrator, Photoshop, Adobe Dimension, Procreate, Webflow",
    roles: "Brand Designer, Graphic Designer, Illustrator, Marketing Strategist, Web desinger",
    problem: [
      "Problem",
      "In a world where health and sustainability are becoming personal priorities, young consumers are searching for trustworthy products that resonate with their values. However, the market for probiotic sodas is cluttered with options that often feel disconnected, generic, or unclear, lacking the transparency and authenticity that today's wellness-minded consumers desire.",
    ],
    solution: [
      "Solution",
      "Bubble is a probiotic soda brand that focuses on transparency, authenticity, and emotional connection. It aims to bridge the gap between wellness trends and consumer trust by offering a credible and enjoyable product that aligns with the values of its consumers.",
      "The design behind bubble is a vibrant celebration of wellness, flavor, and fun. With its bold, bubbly typeface and color palette, the label instantly grabs attention while evoking the playful fizz of soda.",
      "Inspired by natural ingredients and dynamic flavor pairings like Cayenne + Peach, the visual identity is both youthful and energetic, blending organic textures with sleek modern typography. ",
      "The label design emphasizes approachability and transparency, featuring a clean layout for nutrition facts, icons for health benefits, and a QR code that invites consumers into the “bubble revolution.” The overall aesthetic positions bubble as a fresh, health-conscious alternative to traditional sodas—without sacrificing taste or joy.",
    ],
    images: [
      media("p3-1.jpg"),
      media("p3-2.jpg"),
      media("p3-stack1.png"),
      media("p3-stack2.png"),
      media("p3-stack3.png"),
      media("p3-stack4.png"),
      media("p3-stack5.png"),
      media("p3-3.jpg"),
      media("p3-4.jpg"),
      media("p3-5.jpg"),
      media("p3-6.jpg"),
      media("p3-7.jpg"),
    ],
  },
  {
    index: 3,
    id: "bubble-environmental",
    reference: "environmental",
    title: "bubble, pop-up",
    category: "Environmental Design",
    timeframe: "12 weeks (January – March 2025)",
    tools: "Procreate, Illustrator, Photoshop, Adobe Dimension, Blender",
    problem: [
      "Problem",
      "How can I create brand awareness for bubble, a probiotic soda, in a saturated market?",
    ],
    roles: "Graphic Designer and Environmental Designer",
    solution: [
      "Solution",
      "The (Re)Charging Station is a branded activation space at the Bumbershoot Festival in Seattle Center. It provides festival-goers with a place to relax, recharge their phones, and enjoy a complimentary probiotic soda.",
      "The station creates an inviting and energetic atmosphere that feels modern and joyful, effectively bringing the bubble brand experience to life.",
      "I used the vibrant colors of the brand to create an energetic environment. The main concept behind the environmental advertisement focuses on the fizz of the soda and how a bubble is an essential part of the brand's identity. For this reason, I designed all the elements to resemble overlapping bubbles.",
      "I enhanced the solution with a bus wrap advertisement that showcases the brand's vibrant colors. The design highlights the freshness and effervescence of the product. The messages “JOIN THE BUBBLE REVOLUTION!” and “NO GUILT, ALL FLAVOR!” are intended to foster a sense of community while promoting the soda's health benefits."
    ],
    images: [
      media("p4-1.jpg"),
      media("p4-2.jpg"),
      media("p4-stack1.png"),
      media("p4-stack2.png"),
      media("p4-stack3.png"),
      media("p4-stack4.png"),
      media("p4-stack5.png"),
      media("p4-3.jpg"),
      media("p4-4.jpg"),
      media("p4-5.jpg"),
      media("p4-6.jpg"),
      media("p4-7.jpg"),
    ],
  },
  {
    index: 4,
    id: "rebloom",
    reference: "branding + UX+UI",
    title: "ReBloom",
    category: "Branding + UX/UI",
    timeframe: "12 weeks (September – December 2024)",
    tools: "Figma, Midjourney, Photoshop, Illustrator",
    roles: "Researcher, Graphic Designer, Web Designer",
    problem: [
      "Problem",
      "Traditional flower delivery services can be expensive, overwhelming, and wasteful, often leading to consumer decision fatigue. Customers have to navigate cluttered websites, face high prices, and deal with endless customization options while contributing to environmental waste. At the same time, farmers throw away thousands of “imperfect” flowers every season, contributing to the industry's unsustainable practices.",
    ],
    solution: [
      "Solution",
      "ReBloom is a flower company rooted in the belief that sustainability and beauty can coexist without compromise. By rescuing surplus flowers from the fields of Skagit Valley, ReBloom gives new life to blooms that would otherwise go to waste—transforming excess into joy.",
      "With just three bouquet sizes and a direct-to-consumer model, the brand embraces simplicity to reduce waste, lower costs, and streamline the customer experience.",
      "Each arrangement is packaged in biodegradable materials and delivered through a zero-emissions fleet, reinforcing ReBloom’s mission to minimize environmental impact while maximizing freshness and artistry.",
      "I created not just a brand, but experiences that connect with our community. I developed programs like “Buy One, Surprise One” and “Petal to Soil” to engage customers even after their purchase. These initiatives provide two compelling reasons to trust and support our mission: the joy of surprising someone with a bouquet at local hospitals and community centers, and the positive impact of composting floral waste."
    ],
    images: [
      media("p5-1.jpg"),
      media("p5-2.jpg"),
      media("p5-stack1.png"),
      media("p5-stack2.png"),
      media("p5-stack3.png"),
      media("p5-stack4.png"),
      media("p5-stack5.png"),
      media("p5-3.jpg"),
      media("p5-4.jpg"),
      media("p5-5.jpg"),
      media("p5-6.jpg"),
      media("p5-7.jpg"),
    ],
  },
  {
    index: 5,
    id: "exploration",
    reference: "other works",
    title: "Creative Exploration",
    category: "Visual Design",
    timeframe: "September 2023 – Mar 2025)",
    tools: "Illustrator, InDesign, Photoshop, Procreate, AfterEffects",
    roles: "Graphic Designer, Visual Designer",
    problem: "",
    solution: "",
    images: [
      media("p6-1.jpg"),
      media("p6-2.jpg"),
      media("p6-stack1.png"),
      media("p6-stack2.png"),
      media("p6-stack3.png"),
      media("p6-stack4.png"),
      media("p6-stack5.png"),
      media("p6-3.jpg"),
      media("p6-4.jpg"),
      media("p6-5.jpg"),
      media("p6-6.jpg"),
      media("p6-7.jpg"),


    ],
  },
];
